// ═══════════════════════════════════════════════════════════════════
//  GÖGN — allt efni síðunnar á einum stað.
//  Uppfærðu MARKADUR þegar nýjar tölur koma frá Seðlabanka/Hagstofu.
// ═══════════════════════════════════════════════════════════════════

const UPPFAERT = "24. september 2026";

// Hagtölur sem ekki eru sóttar sjálfkrafa. Gengi er sótt lifandi (sjá app.js).
const MARKADUR = {
  styrivextir:  { gildi: 8.0,   dags: "19. ágúst 2026", heimild: "https://sedlabanki.is/" },
  verdbolga:    { gildi: 5.6,   dags: "ágúst 2026",     heimild: "https://hagstofa.is/talnaefni/efnahagur/verdlag/" },
  vnv:          { gildi: 694.6, dags: "ágúst 2026",     heimild: "https://hagstofa.is/talnaefni/efnahagur/verdlag/visitala-neysluverds/" },
  verdbolgumarkmid: 2.5,
  // Varagildi ef ekki næst í gengisþjónustu
  gengiVara: { EUR: 138.0, USD: 120.9, GBP: 160.6, DKK: 18.46, NOK: 12.78, SEK: 12.24, dags: "23. sept. 2026" },
};

// Skattar 2026 (Skatturinn)
const SKATTUR = {
  ar: 2026,
  threp: [
    { upp: 498122,   hlutfall: 0.3149 },
    { upp: 1398450,  hlutfall: 0.3799 },
    { upp: Infinity, hlutfall: 0.4629 },
  ],
  personuafslattur: 72492,       // á mánuði
  lifeyrirLaunthegi: 0.04,
  lifeyrirAtvinnurekandi: 0.115,
  fjarmagnstekjuskattur: 0.22,
  heimild: "https://www.skatturinn.is/einstaklingar/stadgreidsla/stadgreidsla/2026/",
};

// Lánareglur Seðlabankans
const LANAREGLUR = {
  vedhlutfall: 0.80, vedhlutfallFyrstu: 0.85,
  greidslubyrdi: 0.35, greidslubyrdiFyrstu: 0.40,
};

const FLOKKAR = {
  grunnur:   { nafn: "Grunnur",   cls: "cat-grunnur" },
  heimili:   { nafn: "Heimilið",  cls: "cat-heimili" },
  hlutabref: { nafn: "Fjárfesting", cls: "cat-hlutabref" },
  lifeyrir:  { nafn: "Lífeyrir",  cls: "cat-lifeyrir" },
  afl:       { nafn: "Lengra komið", cls: "cat-afl" },
};

// Íslenskt talnasnið (1.234.567,89) — óháð tungumálastillingu vafrans
function tala(n, aukastafir = 0, lagm = 0) {
  if (!isFinite(n)) return "–";
  const neg = n < 0;
  let [heil, brot = ""] = Math.abs(n).toFixed(aukastafir).split(".");
  heil = heil.replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  brot = brot.replace(/0+$/, "");
  while (brot.length < lagm) brot += "0";
  return (neg ? "−" : "") + heil + (brot ? "," + brot : "");
}
const pct = n => tala(n, 2, 1) + "%";

// ── HUGTÖK ─────────────────────────────────────────────────────────
// Bættu við nýjum hugtökum hér. `aliases` = önnur leitarorð (t.d. enska).
const HUGTOK = [
  {
    term: "Verðbólga", aliases: ["inflation", "verðlag"], cat: "grunnur",
    hint: "Þegar verðlag á vörum og þjónustu hækkar",
    explanation: "Verðbólga er þegar almennt verðlag hækkar með tímanum, þannig að sama upphæð kaupir minna en áður. Hagstofa Íslands mælir hana mánaðarlega með vísitölu neysluverðs.",
    example: "Ef verðbólga er 5% og þú átt 100.000 kr undir koddanum, kaupa þær eftir ár aðeins það sem um 95.000 kr kaupa í dag.",
    keyNumber: pct(MARKADUR.verdbolga.gildi), keyNumberLabel: `Ársverðbólga á Íslandi (${MARKADUR.verdbolga.dags}). Markmið Seðlabankans er ${pct(MARKADUR.verdbolgumarkmid)}.`,
    tip: "Ef vextir á sparireikningnum eru lægri en verðbólgan tapar sparnaðurinn verðgildi — horfðu á raunvexti.",
    related: ["Vísitala neysluverðs", "Stýrivextir", "Raunvextir", "Verðtrygging"],
  },
  {
    term: "Vísitala neysluverðs", aliases: ["VNV", "CPI", "neysluverðsvísitala"], cat: "grunnur",
    hint: "Mælikvarðinn á verðbólgu á Íslandi",
    explanation: "Vísitala neysluverðs (VNV) mælir verð á dæmigerðri „körfu“ af vörum og þjónustu sem heimili kaupa — mat, húsnæði, samgöngur o.fl. Breyting hennar á 12 mánuðum er ársverðbólgan. Verðtryggð lán fylgja VNV.",
    example: "Í ágúst 2026 hækkaði VNV um 0,20% milli mánaða. Mest munaði um föt (+4,1%) eftir útsölur, en flugfargjöld til útlanda lækkuðu um 9,6%.",
    keyNumber: tala(MARKADUR.vnv.gildi, 1), keyNumberLabel: `Stig VNV (${MARKADUR.vnv.dags}; maí 1988 = 100)`,
    tip: "Hagstofan birtir VNV í lok hvers mánaðar — þá sérðu hvað verðtryggða lánið þitt hækkar.",
    related: ["Verðbólga", "Verðtrygging"],
  },
  {
    term: "Vextir", aliases: ["interest", "vaxtastig"], cat: "grunnur",
    hint: "Verð þess að fá lánaða peninga",
    explanation: "Vextir eru verð þess að fá lánað fé. Þegar þú tekur lán greiðir þú bankanum vexti; þegar þú sparar greiðir bankinn þér vexti. Vextir eru oftast gefnir upp sem hlutfall á ári.",
    example: "Ef þú tekur 1.000.000 kr bílalán á 10% vöxtum greiðir þú um 100.000 kr í vexti fyrsta árið, og minna eftir því sem lánið lækkar.",
    keyNumber: pct(MARKADUR.styrivextir.gildi), keyNumberLabel: `Stýrivextir Seðlabanka Íslands (${MARKADUR.styrivextir.dags})`,
    tip: "Greiddu alltaf fyrst niður skuldir með hæstu vextina (t.d. yfirdrátt og kreditkort) — það er örugg „ávöxtun“.",
    related: ["Stýrivextir", "Raunvextir", "Samsettir vextir"],
  },
  {
    term: "Stýrivextir", aliases: ["meginvextir", "policy rate"], cat: "grunnur",
    hint: "Vextir sem Seðlabankinn notar til að stýra verðbólgu",
    explanation: "Stýrivextir (meginvextir) eru vextir á 7 daga bundnum innlánum bankanna hjá Seðlabanka Íslands. Þeir hafa áhrif á alla aðra vexti í landinu. Þegar verðbólga er of há hækkar peningastefnunefnd vextina til að kæla hagkerfið.",
    example: "Seðlabankinn hækkaði vexti í 9,25% árið 2023 og lækkaði þá svo í 7,25%. Þegar verðbólga fór aftur yfir 5% árið 2026 hækkaði hann þá þrisvar — síðast í 8,0% í ágúst.",
    keyNumber: pct(MARKADUR.styrivextir.gildi), keyNumberLabel: `Stýrivextir (${MARKADUR.styrivextir.dags})`,
    tip: "Hærri stýrivextir = dýrari óverðtryggð lán en betri innlánsvextir. Fylgstu með vaxtaákvörðunardögum Seðlabankans.",
    related: ["Seðlabanki", "Verðbólga", "Vextir"],
  },
  {
    term: "Raunvextir", aliases: ["real interest rate", "raunávöxtun"], cat: "grunnur",
    hint: "Vextir að frádreginni verðbólgu",
    explanation: "Raunvextir eru vextir umfram verðbólgu. Þeir segja til um hvort peningarnir þínir séu í raun að vaxa eða bara að halda í við verðlag. Gróflega: raunvextir ≈ nafnvextir − verðbólga.",
    example: `Sparireikningur með 7% vöxtum þegar verðbólga er ${pct(MARKADUR.verdbolga.gildi)} gefur um ${pct(7 - MARKADUR.verdbolga.gildi)} í raunvexti — og fjármagnstekjuskattur er þá enn ódreginn.`,
    keyNumber: pct(MARKADUR.styrivextir.gildi - MARKADUR.verdbolga.gildi), keyNumberLabel: "Raunstýrivextir í dag (stýrivextir − verðbólga)",
    tip: "Fjármagnstekjuskattur er reiknaður af nafnvöxtum, ekki raunvöxtum — raunávöxtun eftir skatt getur því verið neikvæð.",
    related: ["Vextir", "Verðbólga", "Fjármagnstekjuskattur"],
  },
  {
    term: "Samsettir vextir", aliases: ["vaxtavextir", "compound interest"], cat: "grunnur",
    hint: "Vextir sem reiknast líka af fyrri vöxtum",
    explanation: "Samsettir vextir (vaxtavextir) þýða að vextir leggjast við höfuðstólinn og bera sjálfir vexti næsta tímabil. Með tímanum verður vöxturinn veldisvöxtur — þess vegna skiptir mestu að byrja snemma.",
    example: "20.000 kr á mánuði í 30 ár með 5% ávöxtun verða um 16,6 millj. kr — þar af eru aðeins 7,2 millj. kr innborganir. Afgangurinn eru vextir.",
    keyNumber: "72 ÷ r", keyNumberLabel: "„72-reglan“: ár þar til upphæð tvöfaldast við r% ávöxtun",
    tip: "Prófaðu sparnaðarreiknivélina og sjáðu muninn á því að byrja 25 ára eða 35 ára.",
    related: ["Vextir", "Raunvextir"],
  },
  {
    term: "Verðtrygging", aliases: ["verðtryggt lán", "indexation"], cat: "heimili",
    hint: "Lán eða sparnaður bundinn við verðlag",
    explanation: "Verðtrygging þýðir að höfuðstóll láns eða sparnaðar fylgir vísitölu neysluverðs. Vextir á verðtryggðum lánum eru lægri, en höfuðstóllinn hækkar með verðbólgu. Þetta er nánast séríslenskt fyrirbæri.",
    example: `Ef þú tekur 30 millj. kr verðtryggt íbúðalán og verðbólga er ${pct(MARKADUR.verdbolga.gildi)} bætast um ${Math.round(30 * MARKADUR.verdbolga.gildi / 100 * 10) / 10} millj. kr við höfuðstólinn á einu ári, þó þú greiðir af láninu.`,
    keyNumber: pct(MARKADUR.verdbolga.gildi), keyNumberLabel: "Árleg hækkun höfuðstóls verðtryggðs láns í núverandi verðbólgu",
    tip: "Greiðslubyrði verðtryggðra lána er lægri í byrjun, en eignamyndun hægari. Berðu þau saman í reiknivélinni.",
    related: ["Vísitala neysluverðs", "Fasteignalán", "Verðbólga"],
  },
  {
    term: "Fasteignalán", aliases: ["íbúðalán", "húsnæðislán", "mortgage"], cat: "heimili",
    hint: "Lán með veði í fasteign",
    explanation: "Fasteignalán (íbúðalán) er lán til að kaupa fasteign, þar sem eignin sjálf er sett að veði. Á Íslandi er hægt að velja milli verðtryggðra og óverðtryggðra lána, með föstum eða breytilegum vöxtum.",
    example: `Íbúð kostar 60 millj. kr. Hámarkslán er ${LANAREGLUR.vedhlutfall * 100}% (48 millj.), eða ${LANAREGLUR.vedhlutfallFyrstu * 100}% (51 millj.) fyrir fyrstu kaupendur. Mismuninn þarftu að eiga sjálf/ur sem útborgun.`,
    keyNumber: `${LANAREGLUR.vedhlutfall * 100}% / ${LANAREGLUR.vedhlutfallFyrstu * 100}%`, keyNumberLabel: "Hámarks veðsetningarhlutfall (almennt / fyrstu kaupendur)",
    tip: "Hærri útborgun sparar þér mikið í vöxtum. Kynntu þér líka hlutdeildarlán HMS ef þú ert að kaupa fyrstu íbúð.",
    related: ["Veðsetningarhlutfall", "Greiðslubyrðarhlutfall", "Verðtrygging", "Hlutdeildarlán"],
  },
  {
    term: "Veðsetningarhlutfall", aliases: ["LTV", "loan to value", "lánshlutfall"], cat: "heimili",
    hint: "Hversu stór hluti eignar er fjármagnaður með láni",
    explanation: "Veðsetningarhlutfall er hlutfall láns af verðmæti eignar. Seðlabankinn setur hámark til að tryggja að fólk eigi eitthvað eigið fé í eigninni ef verð lækkar.",
    example: "Ef íbúð kostar 50 millj. kr og lánið er 40 millj. kr er veðsetningarhlutfallið 80%.",
    keyNumber: `${LANAREGLUR.vedhlutfall * 100}%`, keyNumberLabel: `Hámark almennt (${LANAREGLUR.vedhlutfallFyrstu * 100}% fyrir fyrstu kaupendur)`,
    tip: "Því lægra sem hlutfallið er, því betri kjör geturðu oft fengið.",
    related: ["Fasteignalán", "Greiðslubyrðarhlutfall"],
  },
  {
    term: "Greiðslubyrðarhlutfall", aliases: ["DSTI", "greiðslubyrði"], cat: "heimili",
    hint: "Hversu stór hluti tekna fer í afborganir",
    explanation: "Greiðslubyrðarhlutfall er hlutfall mánaðarlegra afborgana af ráðstöfunartekjum. Seðlabankinn setur hámark á það við veitingu fasteignalána, svo fólk skuldsetji sig ekki um of.",
    example: "Ef útborguð laun eru 600.000 kr á mánuði má greiðslubyrði fasteignaláns almennt ekki fara yfir 210.000 kr (35%).",
    keyNumber: `${LANAREGLUR.greidslubyrdi * 100}% / ${LANAREGLUR.greidslubyrdiFyrstu * 100}%`, keyNumberLabel: "Hámark (almennt / fyrstu kaupendur)",
    tip: "Bankar reikna greiðslubyrði með lágmarksvöxtum í greiðslumati, svo raunverulegt svigrúm getur verið minna en þú heldur.",
    related: ["Fasteignalán", "Veðsetningarhlutfall"],
  },
  {
    term: "Hlutdeildarlán", aliases: ["HMS"], cat: "heimili",
    hint: "Stuðningur ríkisins við fyrstu kaupendur",
    explanation: "Hlutdeildarlán eru veitt af Húsnæðis- og mannvirkjastofnun (HMS) til fyrstu kaupenda og þeirra sem hafa ekki átt íbúð í nokkur ár, undir ákveðnum tekjumörkum. Ríkið lánar hluta kaupverðs án vaxta og afborgana og fær sama hlutfall af söluverði síðar.",
    example: "Ef HMS lánar 20% af 50 millj. kr íbúð og hún er seld seinna á 60 millj. kr, endurgreiðir þú 20% af 60 millj. = 12 millj. kr.",
    keyNumber: "HMS", keyNumberLabel: "Sótt er um á vef HMS — skilyrði og tekjumörk breytast reglulega",
    tip: "Skoðaðu gildandi skilyrði á hms.is áður en þú gerir tilboð.",
    related: ["Fasteignalán"],
  },
  {
    term: "Tekjuskattur", aliases: ["skattþrep", "staðgreiðsla", "income tax"], cat: "heimili",
    hint: "Skattur á launatekjur",
    explanation: "Tekjuskattur (ásamt útsvari) er dreginn af launum í staðgreiðslu. Kerfið er þrepaskipt: hærra hlutfall leggst á tekjur umfram ákveðin mörk. Persónuafsláttur dregst svo frá reiknuðum skatti.",
    example: `Árið ${SKATTUR.ar}: ${pct(31.49)} af fyrstu 498.122 kr, ${pct(37.99)} af næstu 900.328 kr og ${pct(46.29)} af tekjum yfir 1.398.450 kr á mánuði.`,
    keyNumber: pct(31.49), keyNumberLabel: `Lægsta skattþrep ${SKATTUR.ar} (með meðalútsvari)`,
    tip: "Prófaðu launareiknivélina til að sjá hvað þú færð útborgað.",
    related: ["Persónuafsláttur", "Fjármagnstekjuskattur"],
  },
  {
    term: "Persónuafsláttur", aliases: ["personal allowance"], cat: "heimili",
    hint: "Upphæð sem dregst frá reiknuðum skatti",
    explanation: "Persónuafsláttur er föst upphæð sem dregst frá reiknuðum tekjuskatti allra einstaklinga 16 ára og eldri. Hann virkar eins og skattleysismörk. Ónýttan persónuafslátt má færa til maka.",
    example: `Ef reiknaður skattur af launum er 180.000 kr greiðir þú ${tala(180000 - SKATTUR.personuafslattur)} kr eftir að persónuafsláttur (${tala(SKATTUR.personuafslattur)} kr) er dreginn frá.`,
    keyNumber: tala(SKATTUR.personuafslattur) + " kr", keyNumberLabel: `Persónuafsláttur á mánuði (${SKATTUR.ar})`,
    tip: "Ef þú ert í tveimur störfum, láttu aðeins annan vinnuveitandann nýta persónuafsláttinn — annars endarðu með skattskuld.",
    related: ["Tekjuskattur"],
  },
  {
    term: "Fjármagnstekjuskattur", aliases: ["capital gains tax"], cat: "heimili",
    hint: "Skattur á vexti, arð og söluhagnað",
    explanation: "Fjármagnstekjuskattur leggst á tekjur af fjármagni — vexti af innlánum, arð af hlutabréfum og hagnað af sölu verðbréfa.",
    example: "Ef þú kaupir hlutabréf á 100.000 kr og selur á 150.000 kr er hagnaðurinn 50.000 kr og skatturinn 22% = 11.000 kr.",
    keyNumber: "22%", keyNumberLabel: "Fjármagnstekjuskattur á Íslandi",
    tip: "Ákveðið frítekjumark gildir um vexti og arð einstaklinga — kynntu þér það á skatturinn.is.",
    related: ["Tekjuskattur", "Arður", "Raunvextir"],
  },
  {
    term: "Lífeyrissjóður", aliases: ["lífeyrir", "pension"], cat: "lifeyrir",
    hint: "Skyldusparnaður til efri ára",
    explanation: "Lífeyrissjóður er lögbundinn sparnaður sem tryggir þér tekjur þegar þú hættir að vinna, og vernd ef þú missir starfsgetu. Bæði þú og vinnuveitandinn greiðið í sjóðinn af hverjum launum.",
    example: "Af 600.000 kr launum fara 4% frá þér (24.000 kr) og 11,5% frá vinnuveitanda (69.000 kr) — samtals 93.000 kr á mánuði.",
    keyNumber: "15,5%", keyNumberLabel: "Lágmarksiðgjald af launum (4% + 11,5%)",
    tip: "Skoðaðu réttindin þín reglulega á lifeyrisgattin.is — og gleymdu ekki séreigninni.",
    related: ["Séreignarsparnaður"],
  },
  {
    term: "Séreignarsparnaður", aliases: ["viðbótarlífeyrissparnaður", "séreign"], cat: "lifeyrir",
    hint: "Valfrjáls sparnaður með mótframlagi",
    explanation: "Séreignarsparnaður er valfrjáls viðbót við lífeyrissparnað. Þú greiðir allt að 4% af launum og vinnuveitandi bætir við 2% mótframlagi. Iðgjaldið er dregið frá áður en skattur er reiknaður.",
    example: "Af 600.000 kr launum leggur þú 24.000 kr (4%) og vinnuveitandi 12.000 kr (2%) — 36.000 kr á mánuði. Það kostar þig aðeins um 15.000 kr í útborguðum launum vegna skattfrestunar.",
    keyNumber: "+2%", keyNumberLabel: "Mótframlag vinnuveitanda — í raun ókeypis launahækkun",
    tip: "Séreign má nýta skattfrjálst inn á íbúðalán eða til útborgunar í fyrstu íbúð. Ekki láta mótframlagið fara til spillis!",
    related: ["Lífeyrissjóður", "Fasteignalán"],
  },
  {
    term: "Hlutabréf", aliases: ["stocks", "shares", "hlutir"], cat: "hlutabref",
    hint: "Eignarhlutur í fyrirtæki",
    explanation: "Hlutabréf eru eignarhlutir í fyrirtæki. Sem hluthafi áttu rétt á hluta af hagnaði (arði) og getur hagnast ef verðmæti fyrirtækisins eykst — eða tapað ef það minnkar.",
    example: "Ef þú kaupir 100 hluti í Arion banka á Nasdaq Iceland átt þú lítinn hluta bankans og færð arð ef hann greiðir hann út.",
    keyNumber: "7–10%", keyNumberLabel: "Söguleg meðalávöxtun hlutabréfa á ári (nafnávöxtun, alþjóðlega)",
    tip: "Dreifðu áhættunni með sjóðum í stað þess að setja allt í eitt fyrirtæki.",
    related: ["Hlutabréfamarkaður", "Arður", "ETF", "Dreifing fjárfestinga"],
  },
  {
    term: "Skuldabréf", aliases: ["bonds", "ríkisbréf"], cat: "hlutabref",
    hint: "Lán til fyrirtækis eða ríkis",
    explanation: "Skuldabréf er lán sem þú veitir ríki eða fyrirtæki. Útgefandinn lofar að greiða vexti og endurgreiða höfuðstólinn á gjalddaga. Verð skuldabréfa lækkar þegar markaðsvextir hækka.",
    example: "Ríkissjóður gefur út ríkisbréf til að fjármagna sig. Lífeyrissjóðir eru stærstu kaupendurnir, en einstaklingar geta keypt þau í gegnum skuldabréfasjóði.",
    keyNumber: "↑ vextir = ↓ verð", keyNumberLabel: "Gullna reglan um skuldabréf",
    tip: "Skuldabréf eru almennt öruggari en hlutabréf en skila lægri ávöxtun til lengri tíma.",
    related: ["Ávöxtunarkrafa", "Vextir"],
  },
  {
    term: "ETF", aliases: ["kauphallarsjóður", "vísitölusjóður", "index fund", "exchange traded fund"], cat: "hlutabref",
    hint: "Sjóður sem inniheldur mörg hlutabréf",
    explanation: "ETF (kauphallarsjóður) er sjóður sem er skráður á markað og inniheldur mörg verðbréf í einu. Flestir fylgja vísitölu, t.d. S&P 500, og hafa því mjög lágan kostnað.",
    example: "Með einu S&P 500 ETF fjárfestir þú í 500 stærstu fyrirtækjum Bandaríkjanna í einu.",
    keyNumber: "0,03–0,5%", keyNumberLabel: "Dæmigerður árlegur kostnaður ETF",
    tip: "Kostnaður skiptir miklu: 1% árleg þóknun getur étið fjórðung af ávöxtun á 30 árum.",
    related: ["Dreifing fjárfestinga", "Hlutabréf"],
  },
  {
    term: "P/E hlutfall", aliases: ["V/H", "verð/hagnaður", "price to earnings"], cat: "hlutabref",
    hint: "Verð hlutabréfs deilt með hagnaði á hlut",
    explanation: "P/E hlutfall (verð/hagnaður) sýnir hversu dýrt hlutabréf er miðað við hagnað fyrirtækisins. Það er reiknað með því að deila hlutabréfaverði með hagnaði á hlut.",
    example: "Ef hlutabréf kostar 1.000 kr og hagnaður á hlut er 50 kr er P/E hlutfallið 20 — þú greiðir 20 falt árshagnaðinn.",
    keyNumber: "15–25", keyNumberLabel: "Algengt bil P/E á S&P 500 sögulega",
    tip: "Lágt P/E getur þýtt að bréfið sé ódýrt — en líka að markaðurinn búist við minni hagnaði.",
    related: ["Hlutabréf", "Markaðsvirði"],
  },
  {
    term: "Hlutabréfamarkaður", aliases: ["kauphöll", "Nasdaq Iceland", "OMXI15", "OMXI10"], cat: "hlutabref",
    hint: "Þar sem hlutabréf ganga kaupum og sölum",
    explanation: "Hlutabréfamarkaður er þar sem hlutabréf skráðra fyrirtækja eru keypt og seld. Á Íslandi er það Nasdaq Iceland (Kauphöllin), þar sem m.a. bankarnir, Icelandair, Alvotech og JBT Marel eru skráð.",
    example: "OMXI15 er helsta vísitala Kauphallarinnar og fylgir 15 veltumestu félögunum. Ef hún hækkar um 1% hafa þau að meðaltali hækkað um 1%.",
    keyNumber: "~27", keyNumberLabel: "Félög á aðalmarkaði Nasdaq Iceland (2026)",
    tip: "Íslenski markaðurinn er lítill — dreifðu líka á erlenda markaði.",
    related: ["Hlutabréf", "IPO"],
  },
  {
    term: "Arður", aliases: ["dividend", "arðgreiðsla"], cat: "hlutabref",
    hint: "Hagnaður sem fyrirtæki greiðir hluthöfum",
    explanation: "Arður er sá hluti hagnaðar sem fyrirtæki greiðir til hluthafa. Ekki öll fyrirtæki greiða arð — sum nota hagnaðinn frekar til vaxtar.",
    example: "Ef þú átt 1.000 hluti og fyrirtækið greiðir 5 kr í arð á hlut færðu 5.000 kr, að frádregnum 22% fjármagnstekjuskatti.",
    keyNumber: "2–5%", keyNumberLabel: "Algeng arðgreiðsluávöxtun á ári",
    tip: "Of hátt útgreiðsluhlutfall (payout ratio) getur verið ósjálfbært.",
    related: ["Hlutabréf", "Fjármagnstekjuskattur"],
  },
  {
    term: "Markaðsvirði", aliases: ["market cap"], cat: "hlutabref",
    hint: "Heildarverðmæti fyrirtækis á markaði",
    explanation: "Markaðsvirði er heildarverðmæti skráðs fyrirtækis: fjöldi hluta margfaldaður með hlutabréfaverði.",
    example: "Fyrirtæki með 1 milljarð hluta sem kosta 100 kr hver er metið á 100 milljarða kr.",
    keyNumber: "10 ma. $", keyNumberLabel: "Viðmið fyrir „large-cap“ fyrirtæki",
    tip: "Hátt markaðsvirði þýðir ekki að fyrirtækið sé góð fjárfesting — verðið skiptir máli.",
    related: ["P/E hlutfall", "Hlutabréf"],
  },
  {
    term: "Dreifing fjárfestinga", aliases: ["diversification", "áhættudreifing"], cat: "hlutabref",
    hint: "Ekki setja öll eggin í eina körfu",
    explanation: "Dreifing þýðir að skipta fjárfestingum á margar eignir, geira og markaði til að minnka áhættu. Ef eitt fer illa skaðar það ekki allan sparnaðinn.",
    example: "Í stað þess að kaupa eitt hlutabréf kaupir þú alþjóðlegan vísitölusjóð með þúsundum fyrirtækja.",
    keyNumber: "15–20+", keyNumberLabel: "Lágmarksfjöldi ólíkra hlutabréfa til góðrar dreifingar",
    tip: "Dreifðu líka yfir tíma: reglulegur mánaðarlegur sparnaður jafnar út sveiflur.",
    related: ["ETF", "Hlutabréf"],
  },
  {
    term: "IPO", aliases: ["frumútboð", "skráning á markað"], cat: "hlutabref",
    hint: "Þegar fyrirtæki fer fyrst á markað",
    explanation: "IPO (frumútboð) er þegar fyrirtæki býður hlutabréf sín almenningi í fyrsta sinn og er skráð á markað.",
    example: "Í maí 2025 seldi ríkið síðasta hlut sinn í Íslandsbanka í almennu útboði þar sem einstaklingar fengu forgang.",
    keyNumber: "Forgangur", keyNumberLabel: "Í íslenskum útboðum fá einstaklingar stundum forgang",
    tip: "Rannsóknir sýna að nýskráð félög skila oft lakari ávöxtun en markaðurinn til langs tíma.",
    related: ["Hlutabréfamarkaður"],
  },
  {
    term: "Ávöxtunarkrafa", aliases: ["yield", "krafa"], cat: "hlutabref",
    hint: "Ávöxtun sem fjárfestar krefjast",
    explanation: "Ávöxtunarkrafa er sú ávöxtun sem fjárfestar krefjast af fjárfestingu miðað við áhættu. Á skuldabréfamarkaði er hún sú ávöxtun sem fæst ef bréfið er keypt á núverandi verði og haldið til gjalddaga.",
    example: "Ef ávöxtunarkrafa ríkisbréfa hækkar úr 7% í 8% lækkar verð eldri bréfa, því ný bréf bjóða betri kjör.",
    keyNumber: "Öfugt samband", keyNumberLabel: "Krafa hækkar ↔ verð lækkar",
    tip: "Hærri áhætta kallar á hærri kröfu — enginn fær há ávöxtun án áhættu.",
    related: ["Skuldabréf"],
  },
  {
    term: "Gengi", aliases: ["exchange rate", "gjaldmiðill", "króna"], cat: "grunnur",
    hint: "Verð gjaldmiðils í öðrum gjaldmiðli",
    explanation: "Gengi er verð eins gjaldmiðils mælt í öðrum. Þegar krónan veikist þarf fleiri krónur fyrir hverja evru eða dollar, og innfluttar vörur verða dýrari.",
    example: "Ef EUR/ISK er 138 kostar 1 evra 138 krónur. Hlutur sem kostar 100 € erlendis kostar þá 13.800 kr.",
    keyNumber: tala(MARKADUR.gengiVara.EUR, 2), keyNumberLabel: `EUR/ISK (${MARKADUR.gengiVara.dags}) — sjá lifandi gengi í gjaldmiðlabreyti`,
    tip: "Gengisbreytingar hafa mikil áhrif á verðbólgu á Íslandi því við flytjum mikið inn.",
    related: ["Verðbólga", "Gengisáhætta"],
  },
  {
    term: "Gengisáhætta", aliases: ["currency risk"], cat: "afl",
    hint: "Áhættan af því að gengi breytist",
    explanation: "Gengisáhætta er hættan á tapi vegna breytinga á gengi. Hún snertir alla sem eiga eignir eða skuldir í erlendum gjaldmiðlum.",
    example: "Fyrir hrunið 2008 tóku margir Íslendingar gengistryggð lán. Þegar krónan féll um tæpan helming tvöfölduðust lánin í krónum talið.",
    keyNumber: "2008", keyNumberLabel: "Árið sem gengistryggð lán urðu mörgum að falli",
    tip: "Aldrei taka lán í öðrum gjaldmiðli en þú hefur tekjur í.",
    related: ["Gengi", "Afleiður"],
  },
  {
    term: "Seðlabanki", aliases: ["Seðlabanki Íslands", "central bank"], cat: "grunnur",
    hint: "Banki bankanna og vörður verðlags",
    explanation: "Seðlabanki Íslands ber ábyrgð á stöðugu verðlagi og fjármálastöðugleika. Hann ákveður stýrivexti, gefur út krónuna, varðveitir gjaldeyrisforðann og hefur frá 2020 einnig annast fjármálaeftirlit.",
    example: "Peningastefnunefnd tilkynnir vaxtaákvarðanir á fyrirfram auglýstum dögum. Í ágúst 2026 hækkaði hún vexti í 8,0% vegna þrálátrar verðbólgu.",
    keyNumber: "2,5%", keyNumberLabel: "Verðbólgumarkmið Seðlabankans",
    tip: "Yfirlýsingar peningastefnunefndar gefa vísbendingu um hvert vextir stefna.",
    related: ["Stýrivextir", "Verðbólga"],
  },
  {
    term: "Landsframleiðsla", aliases: ["GDP", "VLF", "Þjóðarframleiðsla", "hagvöxtur"], cat: "grunnur",
    hint: "Heildarverðmæti framleiðslu í landinu",
    explanation: "Verg landsframleiðsla (VLF, e. GDP) mælir heildarverðmæti allra vara og þjónustu sem framleidd er í landinu á ári. Breyting hennar að raunvirði er hagvöxtur.",
    example: "VLF Íslands var um 4.956 milljarðar kr árið 2025, eða um 13 millj. kr á hvern íbúa.",
    keyNumber: "~4.956 ma. kr", keyNumberLabel: "VLF Íslands 2025 (bráðabirgðatölur Hagstofu)",
    tip: "Tveir ársfjórðungar í röð með samdrætti eru oft kallaðir samdráttarskeið (e. recession).",
    related: ["Verðbólga"],
  },
  {
    term: "Neyðarsjóður", aliases: ["varasjóður", "emergency fund", "lausafé"], cat: "heimili",
    hint: "Varasjóður fyrir óvænt útgjöld",
    explanation: "Neyðarsjóður er sparnaður á aðgengilegum reikningi sem grípa má til ef eitthvað óvænt gerist — atvinnumissir, bílaviðgerð eða veikindi. Hann á að koma á undan áhættusamari fjárfestingum.",
    example: "Ef mánaðarleg útgjöld þín eru 400.000 kr ætti neyðarsjóður að vera 1,2–2,4 millj. kr.",
    keyNumber: "3–6 mán.", keyNumberLabel: "Mælt með útgjöldum í neyðarsjóði",
    tip: "Geymdu neyðarsjóðinn á óbundnum innlánsreikningi — ekki í hlutabréfum.",
    related: ["Lausafjárstaða", "Dreifing fjárfestinga"],
  },
  {
    term: "Lausafjárstaða", aliases: ["liquidity", "seljanleiki"], cat: "grunnur",
    hint: "Hversu fljótt má breyta eign í peninga",
    explanation: "Lausafé lýsir því hversu auðveldlega og fljótt má breyta eign í reiðufé án verðfalls. Innlán eru mjög laus, hlutabréf nokkuð, fasteignir lítið.",
    example: "Þú getur selt hlutabréf í sjóði á nokkrum dögum, en sala á íbúð getur tekið marga mánuði.",
    keyNumber: "Dagar vs. mánuðir", keyNumberLabel: "Verðbréf vs. fasteign",
    tip: "Fyrirtæki geta farið í þrot vegna lausafjárskorts þótt þau séu rekin með hagnaði.",
    related: ["Neyðarsjóður", "Sjóðstreymi"],
  },
  {
    term: "Sjóðstreymi", aliases: ["cash flow", "fjárstreymi"], cat: "afl",
    hint: "Peningaflæði inn og út úr rekstri",
    explanation: "Sjóðstreymi sýnir raunverulegt peningaflæði inn og út úr fyrirtæki (eða heimili). Jákvætt sjóðstreymi þýðir að meira kemur inn en fer út.",
    example: "Verslun fær 2 millj. kr í sölu en greiðir 1,5 millj. kr í leigu, laun og vörur — sjóðstreymið er +500.000 kr.",
    keyNumber: "Jákvætt", keyNumberLabel: "Grunnskilyrði heilbrigðs reksturs",
    tip: "Fyrirtæki getur sýnt hagnað á pappír en samt farið í þrot ef sjóðstreymið er neikvætt.",
    related: ["Lausafjárstaða", "Vaxtaþekja"],
  },
  {
    term: "Vaxtaþekja", aliases: ["interest coverage"], cat: "afl",
    hint: "Getur fyrirtækið borgað vextina sína?",
    explanation: "Vaxtaþekja mælir hversu oft rekstrarhagnaður (EBIT) dugar fyrir vaxtagjöldum. Hún segir til um fjárhagslegan styrk fyrirtækis.",
    example: "Fyrirtæki með 10 millj. kr rekstrarhagnað og 2 millj. kr vaxtagjöld hefur vaxtaþekju 5x.",
    keyNumber: "< 1,5x", keyNumberLabel: "Viðvörunarmerki um erfiða skuldastöðu",
    tip: "Skoðaðu vaxtaþekju áður en þú kaupir skuldabréf fyrirtækis.",
    related: ["Sjóðstreymi", "Skuldsetning"],
  },
  {
    term: "Arðsemi", aliases: ["ROI", "ávöxtun", "arðsemi eigin fjár", "ROE"], cat: "grunnur",
    hint: "Hlutfall hagnaðar af fjárfestingu",
    explanation: "Arðsemi mælir hversu mikið þú færð til baka miðað við það sem þú lagðir í. Arðsemi eigin fjár (ROE) er algengur mælikvarði á banka og fyrirtæki.",
    example: "Ef þú kaupir fyrir 100.000 kr og selur fyrir 120.000 kr ári síðar er arðsemin 20%.",
    keyNumber: "(hagnaður ÷ fjárfesting)", keyNumberLabel: "Einfaldasta formúlan",
    tip: "Taktu alltaf tillit til verðbólgu, skatta og kostnaðar til að fá raunverulega arðsemi.",
    related: ["Raunvextir"],
  },
  {
    term: "Afleiður", aliases: ["derivatives", "valréttur", "framvirkur samningur"], cat: "afl",
    hint: "Samningar sem byggja á verði annarrar eignar",
    explanation: "Afleiður eru fjármálasamningar þar sem verðmætið ræðst af annarri eign — hlutabréfi, gjaldmiðli, vöxtum eða hrávöru. Þær eru notaðar til að verjast áhættu, en líka til spákaupmennsku.",
    example: "Íslenskt útflutningsfyrirtæki sem fær tekjur í dollurum getur gert framvirkan gjaldeyrissamning til að verja sig gegn veikingu dollarans.",
    keyNumber: "Há áhætta", keyNumberLabel: "Afleiður geta tapað meira en upphaflegri fjárhæð",
    tip: "Byrjendur ættu að forðast afleiður.",
    related: ["Gengisáhætta", "Skuldsetning"],
  },
  {
    term: "Skuldsetning", aliases: ["leverage", "vogun", "gírun"], cat: "afl",
    hint: "Að nota lánsfé til að stækka fjárfestingu",
    explanation: "Skuldsetning (vogun) er að nota lánsfé til að auka fjárfestingu umfram eigið fé. Hún margfaldar bæði hagnað og tap.",
    example: "Íbúð keypt með 20% eigin fé er 5x skuldsett: ef verðið hækkar um 10% eykst eigið fé um 50% — en lækki það um 10% tapast helmingurinn.",
    keyNumber: "5x", keyNumberLabel: "Skuldsetning við 80% veðsetningu",
    tip: "Skuldsetning er tvíeggjað sverð — íslenska bankahrunið 2008 er skýrt dæmi.",
    related: ["Fasteignalán", "Vaxtaþekja"],
  },
  {
    term: "Vogunarsjóður", aliases: ["hedge fund"], cat: "afl",
    hint: "Sjóður með flóknar fjárfestingaaðferðir",
    explanation: "Vogunarsjóður er fjárfestingarsjóður sem notar flóknar aðferðir — skortsölu, skuldsetningu og afleiður — til að ná ávöxtun óháð markaðnum. Hann er yfirleitt aðeins aðgengilegur fagfjárfestum.",
    example: "Bridgewater Associates, stofnaður af Ray Dalio, er einn stærsti vogunarsjóður heims.",
    keyNumber: "2 / 20", keyNumberLabel: "Klassísk þóknun: 2% á ári + 20% af hagnaði",
    tip: "Flestir vogunarsjóðir ná ekki að slá einfalda vísitölusjóði yfir langan tíma, eftir kostnað.",
    related: ["Afleiður", "Skuldsetning"],
  },
  {
    term: "Rafmynt", aliases: ["bitcoin", "crypto", "rafeyrir", "dulmynt"], cat: "afl",
    hint: "Stafrænn gjaldmiðill án miðstýringar",
    explanation: "Rafmynt er stafrænn gjaldmiðill sem notar dulritun og dreifða færsluskrá (bálkakeðju) í stað banka eða ríkis. Verðið ræðst eingöngu af framboði og eftirspurn og sveiflast mikið.",
    example: "Bitcoin hefur nokkrum sinnum fallið um 50–80% frá hápunkti áður en það náði sér aftur.",
    keyNumber: "21 milljón", keyNumberLabel: "Hámarksfjöldi Bitcoin sem verður til",
    tip: "Fjárfestu aldrei meira í rafmynt en þú ræður við að tapa að fullu.",
    related: ["Dreifing fjárfestinga"],
  },
  {
    term: "Hlutafélag (hf.)", aliases: ["hf", "hlutafélag"], cat: "grunnur",
    hint: "Félagaform sem má skrá á markað",
    explanation: "Hlutafélag er félag þar sem hlutafé skiptist í hluti og hluthafar bera takmarkaða ábyrgð — þeir geta aðeins tapað því sem þeir lögðu í félagið. Aðeins hf. geta verið skráð á hlutabréfamarkað.",
    example: "Arion banki hf., Icelandair Group hf. og Hagar hf. eru hlutafélög skráð á Nasdaq Iceland.",
    keyNumber: "4.000.000 kr", keyNumberLabel: "Lágmarkshlutafé við stofnun hf.",
    tip: "Hlutafélag þarf að hafa stjórn með minnst þremur mönnum og endurskoðanda.",
    related: ["Einkahlutafélag (ehf.)", "Hlutabréfamarkaður"],
  },
  {
    term: "Einkahlutafélag (ehf.)", aliases: ["ehf"], cat: "grunnur",
    hint: "Algengasta félagaformið á Íslandi",
    explanation: "Einkahlutafélag er algengasta félagaformið á Íslandi. Eins og í hf. bera eigendur takmarkaða ábyrgð, en kröfur um hlutafé og stjórnun eru minni.",
    example: "Flest lítil og meðalstór fyrirtæki — kaffihúsið á horninu eða fimm manna tæknifyrirtæki — eru ehf.",
    keyNumber: "500.000 kr", keyNumberLabel: "Lágmarkshlutafé við stofnun ehf.",
    tip: "Einn einstaklingur getur stofnað ehf. og verið eini stjórnarmaðurinn.",
    related: ["Hlutafélag (hf.)"],
  },
];

// ── SPURNINGAKEPPNI ────────────────────────────────────────────────
const SPURNINGAR = [
  { q: "Hvað þýðir verðbólga?", opts: ["Hlutabréfaverð hækkar", "Almennt verðlag hækkar", "Bankavextir hækka", "Krónan styrkist"], correct: 1,
    explanation: "Verðbólga er þegar almennt verðlag hækkar — sama upphæð kaupir minna." },
  { q: "Hversu hátt er lágmarksiðgjald í lífeyrissjóð samtals?", opts: ["8%", "12%", "15,5%", "20%"], correct: 2,
    explanation: "4% frá launþega og 11,5% frá vinnuveitanda = 15,5%." },
  { q: "Hvað er ETF?", opts: ["Tegund lífeyrissjóðs", "Skráður sjóður með mörgum verðbréfum", "Erlend gjaldeyrisviðskipti", "Tegund skuldabréfs"], correct: 1,
    explanation: "ETF (kauphallarsjóður) er skráður sjóður sem inniheldur mörg verðbréf í einu." },
  { q: "Hvað gerir Seðlabankinn yfirleitt þegar verðbólga er of há?", opts: ["Lækkar stýrivexti", "Hækkar stýrivexti", "Prentar fleiri seðla", "Kaupir hlutabréf"], correct: 1,
    explanation: "Hærri vextir gera lán dýrari og draga úr eftirspurn, sem kælir verðbólguna." },
  { q: "Hvað þýðir P/E hlutfall 20?", opts: ["Bréfið hefur hækkað um 20%", "Þú greiðir 20 falt árshagnað á hlut", "Fyrirtækið greiðir 20% arð", "Fyrirtækið er 20 ára"], correct: 1,
    explanation: "P/E = verð ÷ hagnaður á hlut." },
  { q: "Hvað gerist við höfuðstól verðtryggðs láns þegar verðbólga er há?", opts: ["Hann lækkar", "Hann hækkar", "Ekkert", "Hann frystist"], correct: 1,
    explanation: "Höfuðstóllinn fylgir vísitölu neysluverðs og hækkar því með verðbólgu." },
  { q: "Hvaða ár féllu stóru íslensku bankarnir þrír?", opts: ["2001", "2006", "2008", "2011"], correct: 2,
    explanation: "Glitnir, Landsbankinn og Kaupþing féllu í október 2008." },
  { q: "Hvað er verðbólgumarkmið Seðlabanka Íslands?", opts: ["0%", "2,5%", "4%", "5%"], correct: 1,
    explanation: "Markmiðið hefur verið 2,5% ársverðbólga síðan 2001." },
  { q: "Hvert er lágmarkshlutafé einkahlutafélags (ehf.)?", opts: ["100.000 kr", "500.000 kr", "4.000.000 kr", "Ekkert lágmark"], correct: 1,
    explanation: "Lágmarkshlutafé ehf. er 500.000 kr; fyrir hf. er það 4.000.000 kr." },
  { q: "Hvað er fjármagnstekjuskattur á Íslandi?", opts: ["10%", "15%", "22%", "31,49%"], correct: 2,
    explanation: "Fjármagnstekjuskattur er 22% af vöxtum, arði og söluhagnaði." },
  { q: "Hversu hátt mótframlag greiðir vinnuveitandi í séreignarsparnað?", opts: ["0%", "1%", "2%", "4%"], correct: 2,
    explanation: "Ef þú greiðir í séreign bætir vinnuveitandinn við 2% mótframlagi." },
  { q: "Hvað er hámarks veðsetningarhlutfall fyrir fyrstu kaupendur?", opts: ["70%", "80%", "85%", "100%"], correct: 2,
    explanation: "85% fyrir fyrstu kaupendur, 80% fyrir aðra." },
  { q: "Ef skuldabréfavextir á markaði hækka, hvað gerist við verð eldri skuldabréfa?", opts: ["Hækkar", "Lækkar", "Helst óbreytt", "Tvöfaldast"], correct: 1,
    explanation: "Verð og ávöxtunarkrafa skuldabréfa hreyfast í öfuga átt." },
  { q: "Hvað segir „72-reglan“?", opts: ["Hámarksaldur á lífeyri", "Ár til tvöföldunar ≈ 72 ÷ ávöxtun", "72% skattur", "Lán til 72 mánaða"], correct: 1,
    explanation: "Við 6% ávöxtun tvöfaldast upphæð á um 72 ÷ 6 = 12 árum." },
  { q: "Hvaða stofnun tók við hlutverki Íbúðalánasjóðs árið 2020?", opts: ["Seðlabankinn", "HMS", "Landsbankinn", "Tryggingastofnun"], correct: 1,
    explanation: "Húsnæðis- og mannvirkjastofnun (HMS) tók við húsnæðismálum Íbúðalánasjóðs." },
  { q: "Hvað kallast breyting á vísitölu neysluverðs á 12 mánuðum?", opts: ["Hagvöxtur", "Ársverðbólga", "Stýrivextir", "Gengi"], correct: 1,
    explanation: "Ársverðbólga er 12 mánaða breyting á VNV." },
  { q: "Af hverju er dreifing fjárfestinga mikilvæg?", opts: ["Hún tryggir hagnað", "Hún minnkar áhættu", "Hún lækkar skatta", "Hún er skylda"], correct: 1,
    explanation: "Dreifing minnkar áhrif þess að einstök fjárfesting fari illa." },
  { q: "Hvað er sjóðstreymi?", opts: ["Hagnaður á pappír", "Raunverulegt peningaflæði inn og út", "Hlutabréfaverð", "Vaxtastig"], correct: 1,
    explanation: "Sjóðstreymi er raunverulegt peningaflæði — ekki bókhaldslegur hagnaður." },
];

// ── SAGA ───────────────────────────────────────────────────────────
const SAGA = [
  { ar: "1602", titill: "Fyrsta hlutafélagið", texti: "Hollenska Austur-Indíafélagið (VOC) gaf út hlutabréf sem almenningur gat keypt og verslað með í Amsterdam — upphaf hlutabréfamarkaða eins og við þekkjum þá." },
  { ar: "1886", titill: "Landsbankinn stofnaður", texti: "Landsbanki Íslands tók til starfa í Reykjavík og varð fyrsti banki landsins. Hann gaf lengi út íslenska seðla, áður en Seðlabankinn var stofnaður 1961." },
  { ar: "1907", titill: "Bankakreppan í Bandaríkjunum", texti: "Bankaáhlaup skóku New York og auðmaðurinn J.P. Morgan bjargaði bankakerfinu nánast einn. Í kjölfarið var Seðlabanki Bandaríkjanna (Federal Reserve) stofnaður árið 1913." },
  { ar: "1929", titill: "Hrunið mikla", texti: "Hrunið á Wall Street leiddi til kreppunnar miklu. Dow Jones-vísitalan féll um 89% frá hápunkti til botns 1932 og milljónir misstu vinnuna." },
  { ar: "1944", titill: "Bretton Woods", texti: "44 þjóðir sömdu um nýtt gjaldmiðlakerfi þar sem dollarinn var bundinn gulli og aðrir gjaldmiðlar dollaranum. Alþjóðagjaldeyrissjóðurinn og Alþjóðabankinn voru stofnaðir." },
  { ar: "1971", titill: "Gulltengingin rofin", texti: "Richard Nixon tilkynnti að ekki yrði lengur hægt að skipta dollurum í gull. Bretton Woods-kerfið leið undir lok og fljótandi gengi tók við." },
  { ar: "1981", titill: "Nýja krónan", texti: "Eftir áratug óðaverðbólgu voru tvö núll skorin af krónunni: 100 gamlar krónur urðu að 1 nýrri. Verðbólga hér fór yfir 80% árið 1983." },
  { ar: "1987", titill: "Svarti mánudagurinn", texti: "19. október 1987 féll Dow Jones um 22,6% á einum degi — mesta dagslækkun sögunnar. Sjálfvirk viðskiptakerfi mögnuðu fallið." },
  { ar: "2000", titill: "Netbólan springur", texti: "Netfyrirtæki án tekna voru metin á milljarða. Þegar bólan sprakk 2000–2002 tapaðist um 5 billjónir dala af markaðsvirði. Amazon féll um 90% en lifði af." },
  { ar: "2001", titill: "Verðbólgumarkmið tekið upp", texti: "Seðlabanki Íslands tók upp verðbólgumarkmið (2,5%) og krónan fór á flot. Það er enn grunnur peningastefnunnar í dag." },
  { ar: "2008", titill: "Íslenska bankahrunið", texti: "Glitnir, Landsbankinn og Kaupþing féllu á einni viku í október. Efnahagsreikningar bankanna voru orðnir um tífaldir á við landsframleiðslu. Neyðarlög, gjaldeyrishöft og IMF-áætlun fylgdu." },
  { ar: "2009", titill: "Bitcoin fæðist", texti: "Satoshi Nakamoto — dulnefni einstaklings eða hóps — setti Bitcoin af stað. Árið 2010 greiddi maður 10.000 bitcoin fyrir tvær pizzur." },
  { ar: "2017", titill: "Gjaldeyrishöftum aflétt", texti: "Eftir níu ár voru gjaldeyrishöft á einstaklinga og fyrirtæki að mestu afnumin og Íslendingar gátu aftur fjárfest frjálst erlendis." },
  { ar: "2020", titill: "COVID-hrunið og bati", texti: "Hlutabréfamarkaðir féllu um 34% á 33 dögum. Seðlabankar lækkuðu vexti og dældu inn fé — markaðir náðu fyrra hámarki á um fimm mánuðum. Stýrivextir á Íslandi fóru í 0,75%." },
  { ar: "2023", titill: "Vextir í 9,25%", texti: "Eftir verðbólguskot sem náði 10,2% í byrjun árs hækkaði Seðlabankinn stýrivexti fjórtán sinnum í röð, upp í 9,25% — hæstu vexti frá 2009." },
  { ar: "2025", titill: "Ríkið selur Íslandsbanka", texti: "Í maí seldi ríkið eftirstandandi 45,2% hlut sinn í Íslandsbanka í almennu útboði. Bankinn, sem varð til úr Glitni eftir hrunið, er nú að fullu í einkaeigu." },
];

// ── FYRIRTÆKI ──────────────────────────────────────────────────────
const FYRIRTAEKI = [
  { flokkur: "banki", nafn: "Landsbankinn", fullt: "Landsbankinn hf.", url: "https://www.landsbankinn.is",
    lysing: "Stærsti banki landsins og nær alfarið í eigu ríkisins. Rætur hans liggja aftur til 1886. Keypti TM tryggingar af Kviku í febrúar 2025.",
    stadreyndir: ["Rætur frá 1886", "Í eigu ríkisins (~98%)", "Á TM tryggingar"] },
  { flokkur: "banki", nafn: "Arion banki", fullt: "Arion banki hf. — skráður á Nasdaq Iceland", url: "https://www.arionbanki.is",
    lysing: "Varð til úr Kaupþingi eftir hrunið 2008. Samstæðan inniheldur Vörð tryggingar og sjóðafélagið Stefni. Fyrirhuguð sameining við Kviku var slegin af í apríl 2026 vegna andstöðu Samkeppniseftirlitsins.",
    stadreyndir: ["Stofnaður 2008", "Skráður á markað", "Á Vörð og Stefni"] },
  { flokkur: "banki", nafn: "Íslandsbanki", fullt: "Íslandsbanki hf. — skráður á Nasdaq Iceland", url: "https://www.islandsbanki.is",
    lysing: "Varð til úr Glitni eftir hrunið 2008. Ríkið seldi síðasta hlut sinn í maí 2025 og bankinn er nú að fullu í einkaeigu. Íslandssjóðir eru dótturfélag hans.",
    stadreyndir: ["Stofnaður 2008", "Skráður á markað", "Einkavæddur 2025"] },
  { flokkur: "banki", nafn: "Kvika banki", fullt: "Kvika banki hf. — skráður á Nasdaq Iceland", url: "https://www.kvika.is",
    lysing: "Minni banki sem sérhæfir sig í eignastýringu, fjárfestingarbankaþjónustu og netbankanum Auði. Varð til við samruna MP banka og Straums árið 2015. Seldi TM til Landsbankans 2025.",
    stadreyndir: ["Stofnaður 2015", "Skráður á markað", "Rekur Auði"] },

  { flokkur: "lifeyrir", nafn: "LSR", fullt: "Lífeyrissjóður starfsmanna ríkisins", url: "https://www.lsr.is",
    lysing: "Stærsti lífeyrissjóður landsins. Sjóðfélagar eru einkum starfsmenn ríkis og stofnana þess — kennarar, heilbrigðisstarfsfólk, lögregla og fleiri.",
    stadreyndir: ["Stærsti sjóðurinn", "Opinberir starfsmenn"] },
  { flokkur: "lifeyrir", nafn: "Lífeyrissjóður verzlunarmanna", fullt: "LIVE", url: "https://www.live.is",
    lysing: "Næststærsti lífeyrissjóður landsins, stofnaður af samtökum verslunarfólks. Einn stærsti fjárfestirinn á íslenskum hlutabréfamarkaði.",
    stadreyndir: ["Næststærstur", "Stór hluthafi á markaði"] },
  { flokkur: "lifeyrir", nafn: "Gildi", fullt: "Gildi – lífeyrissjóður", url: "https://www.gildi.is",
    lysing: "Einn þriggja stærstu lífeyrissjóða landsins. Varð til árið 2005 við sameiningu Lífeyrissjóðsins Framsýnar og Lífeyrissjóðs sjómanna. Sjóðfélagar eru m.a. í verkalýðsfélögum og sjómenn.",
    stadreyndir: ["Stofnaður 2005", "Almennur markaður"] },
  { flokkur: "lifeyrir", nafn: "Birta", fullt: "Birta lífeyrissjóður", url: "https://www.birta.is",
    lysing: "Varð til árið 2016 við sameiningu Stafa lífeyrissjóðs og Sameinaða lífeyrissjóðsins. Sjóðfélagar koma víða að, m.a. úr iðnaði.",
    stadreyndir: ["Stofnaður 2016", "Iðnaður o.fl."] },
  { flokkur: "lifeyrir", nafn: "Festa", fullt: "Festa lífeyrissjóður", url: "https://www.festa.is",
    lysing: "Lífeyrissjóður sem varð til við sameiningu sjóða á Suðurnesjum, Suðurlandi og Vesturlandi. Þjónar fyrst og fremst launafólki á þessum svæðum.",
    stadreyndir: ["Landsbyggðin", "Almennur markaður"] },

  { flokkur: "verdbref", nafn: "Nasdaq Iceland", fullt: "Nasdaq Iceland hf. — Kauphöllin", url: "https://www.nasdaqomxnordic.com/",
    lysing: "Hlutabréfamarkaður Íslands, hluti af Nasdaq-samstæðunni. Þar eru m.a. bankarnir, Icelandair, Hagar, Alvotech og JBT Marel skráð. Helsta vísitalan er OMXI15.",
    stadreyndir: ["~27 félög á aðalmarkaði", "OMXI15"] },
  { flokkur: "verdbref", nafn: "Stefnir", fullt: "Stefnir hf. — dótturfélag Arion banka", url: "https://www.arionbanki.is/einstaklingar/sparnadur/sjodir",
    lysing: "Eitt stærsta sjóðastýringarfélag landsins. Rekur fjölda hlutabréfa-, skuldabréfa- og blandaðra sjóða fyrir einstaklinga og fagfjárfesta.",
    stadreyndir: ["Í eigu Arion banka", "Fjöldi sjóða"] },
  { flokkur: "verdbref", nafn: "Landsbréf", fullt: "Landsbréf hf. — dótturfélag Landsbankans", url: "https://www.landsbref.is",
    lysing: "Sjóðastýringarfélag Landsbankans. Rekur verðbréfa- og fjárfestingarsjóði sem eru aðgengilegir í appi og netbanka Landsbankans.",
    stadreyndir: ["Í eigu Landsbankans", "Fjöldi sjóða"] },
  { flokkur: "verdbref", nafn: "Íslandssjóðir", fullt: "Íslandssjóðir hf. — dótturfélag Íslandsbanka", url: "https://www.islandssjodir.is",
    lysing: "Sjóðastýringarfélag Íslandsbanka. Rekur hlutabréfa-, skuldabréfa- og blandaða sjóði, m.a. vinsæla sjóði fyrir reglulegan sparnað.",
    stadreyndir: ["Í eigu Íslandsbanka", "Reglulegur sparnaður"] },

  { flokkur: "trygging", nafn: "Vörður", fullt: "Vörður tryggingar hf. — dótturfélag Arion banka", url: "https://www.vordur.is",
    lysing: "Tryggingafélag í eigu Arion banka sem býður bæði skaðatryggingar og líftryggingar (Vörður líftryggingar).",
    stadreyndir: ["Í eigu Arion banka", "Skaða- og líftryggingar"] },
  { flokkur: "trygging", nafn: "TM", fullt: "TM tryggingar hf. — dótturfélag Landsbankans", url: "https://www.tm.is",
    lysing: "Eitt elsta tryggingafélag landsins (Tryggingamiðstöðin). Landsbankinn keypti félagið af Kviku í febrúar 2025.",
    stadreyndir: ["Stofnað 1956", "Í eigu Landsbankans"] },
  { flokkur: "trygging", nafn: "Sjóvá", fullt: "Sjóvá-Almennar tryggingar hf. — skráð á Nasdaq Iceland", url: "https://www.sjova.is",
    lysing: "Eitt stærsta tryggingafélag landsins með bíla-, heimilis-, líf- og fyrirtækjatryggingar. Skráð á markað.",
    stadreyndir: ["Skráð á markað", "Líf- og skaðatryggingar"] },
  { flokkur: "trygging", nafn: "VÍS", fullt: "VÍS — hluti af Skaga hf.", url: "https://www.vis.is",
    lysing: "Eitt stærsta tryggingafélag landsins. Móðurfélagið heitir nú Skagi og er skráð á Nasdaq Iceland.",
    stadreyndir: ["Móðurfélag: Skagi", "Skráð á markað"] },

  { flokkur: "annad", nafn: "Seðlabanki Íslands", fullt: "Seðlabanki Íslands", url: "https://www.sedlabanki.is",
    lysing: "Setur stýrivexti, gefur út krónuna og vinnur að stöðugu verðlagi og fjármálastöðugleika. Frá 2020 annast hann einnig fjármálaeftirlit, eftir sameiningu við FME.",
    stadreyndir: ["Stofnaður 1961", "Stýrivextir 8,0%", "Fjármálaeftirlit"] },
  { flokkur: "annad", nafn: "HMS", fullt: "Húsnæðis- og mannvirkjastofnun", url: "https://www.hms.is",
    lysing: "Tók við húsnæðishlutverki Íbúðalánasjóðs árið 2020. Veitir m.a. hlutdeildarlán til fyrstu kaupenda, sér um húsnæðisbætur og heldur utan um fasteignaskrá.",
    stadreyndir: ["Stofnuð 2020", "Hlutdeildarlán", "Húsnæðisbætur"] },
];

const FYRIRTAEKI_FLOKKAR = {
  banki:    { nafn: "Viðskiptabankar", merki: "Banki", icon: "🏦", cls: "ftag-banki" },
  lifeyrir: { nafn: "Lífeyrissjóðir", merki: "Lífeyrir", icon: "🏛️", cls: "ftag-lifeyrir" },
  verdbref: { nafn: "Markaður & sjóðir", merki: "Verðbréf", icon: "📊", cls: "ftag-verdabref" },
  trygging: { nafn: "Tryggingafélög", merki: "Trygging", icon: "🛡️", cls: "ftag-trygging" },
  annad:    { nafn: "Opinberar stofnanir", merki: "Stofnun", icon: "🏛", cls: "ftag-annad" },
};

// ── FRÆÐAST ────────────────────────────────────────────────────────
const FRAEDAST = [
  { flokkur: "Kvikmyndir & þættir", items: [
    { e: "🎬", t: "The Big Short", s: "2015 · Kvikmynd", d: "Nokkrir utangarðsmenn sjá fjármálakreppuna 2008 fyrir. Útskýrir flókin hugtök á skemmtilegan hátt.", tag: "beg" },
    { e: "🎬", t: "Margin Call", s: "2011 · Kvikmynd", d: "Ein nótt í fjárfestingarbanka sem uppgötvar að hann er á barmi falls. Frábær innsýn í Wall Street.", tag: "all" },
    { e: "🎬", t: "Inside Job", s: "2010 · Heimildarmynd", d: "Óskarsverðlaunamynd um orsakir kreppunnar 2008 — og fjallar m.a. um Ísland.", tag: "beg" },
    { e: "📺", t: "Succession", s: "2018–2023 · HBO", d: "Valdabarátta í fjölmiðlaveldi. Skemmtileg innsýn í yfirtökur, stjórnarhætti og hluthafafundi.", tag: "all" },
    { e: "📺", t: "WeCrashed", s: "2022 · Apple TV+", d: "Uppgangur og fall WeWork. Sýnir hvernig ofmat á fyrirtæki getur farið úrskeiðis.", tag: "beg" },
    { e: "📺", t: "Dirty Money", s: "2018– · Netflix", d: "Heimildaþættir um fjársvik, blekkingar og fyrirtækjahneyksli.", tag: "all" },
  ]},
  { flokkur: "Bækur", items: [
    { e: "📖", t: "The Psychology of Money", s: "Morgan Housel · 2020", d: "Besta byrjendabókin. Fjallar um hegðun okkar gagnvart peningum frekar en formúlur.", tag: "beg" },
    { e: "📖", t: "A Random Walk Down Wall Street", s: "Burton Malkiel · 1973", d: "Klassísk rök fyrir því að ódýrir vísitölusjóðir slái flesta sérfræðinga til lengri tíma.", tag: "all" },
    { e: "📖", t: "The Little Book of Common Sense Investing", s: "John C. Bogle · 2007", d: "Stofnandi Vanguard útskýrir af hverju kostnaður skiptir öllu. Stutt og hnitmiðuð.", tag: "beg" },
    { e: "📖", t: "The Intelligent Investor", s: "Benjamin Graham · 1949", d: "Biblía virðisfjárfestinga. Warren Buffett kallar hana bestu fjárfestingarbók sem skrifuð hefur verið.", tag: "adv" },
    { e: "📖", t: "Why Iceland?", s: "Ásgeir Jónsson · 2009", d: "Núverandi seðlabankastjóri útskýrir aðdraganda og orsakir íslenska bankahrunsins.", tag: "all" },
    { e: "📖", t: "Skýrsla rannsóknarnefndar Alþingis", s: "Alþingi · 2010", d: "Ítarleg rannsókn á falli bankanna. Aðgengileg ókeypis á vef Alþingis.", tag: "adv" },
  ]},
  { flokkur: "Hlaðvörp", items: [
    { e: "🎙️", t: "Fjármálakastið", s: "Íslenska · vikulega", d: "Íslenskt hlaðvarp um fjármál, efnahagsmál og viðskipti.", tag: "beg" },
    { e: "🎙️", t: "Planet Money", s: "NPR · Enska", d: "Stuttir og skemmtilegir þættir sem útskýra flókin efnahagsmál með sögum.", tag: "beg" },
    { e: "🎙️", t: "Acquired", s: "Ben Gilbert & David Rosenthal · Enska", d: "Ítarlegar sögur stærstu fyrirtækja heims — NVIDIA, Berkshire, LVMH o.fl.", tag: "adv" },
    { e: "🎙️", t: "We Study Billionaires", s: "The Investor's Podcast · Enska", d: "Fjárfestingaraðferðir og hugsunarháttur fremstu fjárfesta heims.", tag: "all" },
    { e: "🎙️", t: "How I Built This", s: "Guy Raz · Enska", d: "Frumkvöðlar segja frá því hvernig þeir byggðu fyrirtækin sín.", tag: "all" },
    { e: "🎙️", t: "Odd Lots", s: "Bloomberg · Enska", d: "Markaðir, hagfræði og fjármálakerfið útskýrt af sérfræðingum. Fyrir lengra komna.", tag: "adv" },
  ]},
];
